package com.hyunjin.kotlinstudy

fun failException(): Nothing {
    throw Exception()
}

fun failLoop() : Nothing {
    while (true) {
        // 생략
    }
}

fun main(args: Array<String>) {

}


